#include "amichat_amiga_gui.h"
#include "amichat_transcript.h"
#include "amichat_amiga_renderer.h"
#ifdef __AMIGA__
#include <exec/types.h>
#include <intuition/intuition.h>
#include <libraries/gadtools.h>
#include <proto/exec.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <stdlib.h>
#include <string.h>
enum { GID_PROMPT=1,GID_SEND,GID_STOP,GID_SCROLL };
struct AmiChatAmigaGUI { AmiChatSession *session; AmiChatAmigaWorker *worker; AmiChatTranscript *transcript; AmiChatAmigaRenderer *renderer; struct Window *window; struct Gadget *gadgets; struct Gadget *prompt; struct Gadget *send; struct Gadget *stop; struct Gadget *status; struct Gadget *scroll; void *visual; };
static void sync_state(AmiChatAmigaGUI *g);
static void sync_scroll(AmiChatAmigaGUI *g);
AmiChatAmigaGUI *AmiChat_AmigaGUIOpen(AmiChatSession*s,AmiChatAmigaWorker*w){AmiChatAmigaGUI*g;struct Gadget*last=0;struct NewGadget ng;if(!s)return 0;g=(AmiChatAmigaGUI*)calloc(1,sizeof(*g));if(!g)return 0;g->session=s;g->worker=w;g->transcript=AmiChat_TranscriptCreate();g->renderer=AmiChat_AmigaRendererCreate();if(!g->transcript||!g->renderer){AmiChat_AmigaGUIClose(g);return 0;}AmiChat_AmigaRendererSetTranscript(g->renderer,g->transcript);g->visual=GetVisualInfoA(NULL,NULL);if(!g->visual){free(g);return 0;}last=CreateContext(&g->gadgets);ng.ng_VisualInfo=g->visual;ng.ng_TextAttr=0;ng.ng_Flags=PLACETEXT_IN;ng.ng_LeftEdge=10;ng.ng_TopEdge=150;ng.ng_Width=430;ng.ng_Height=18;ng.ng_GadgetText=(STRPTR)"Prompt:";ng.ng_GadgetID=GID_PROMPT;ng.ng_UserData=0;g->prompt=CreateGadget(STRING_KIND,last,&ng,GTST_MaxChars,1024,TAG_DONE);last=g->prompt;ng.ng_LeftEdge=450;ng.ng_Width=60;ng.ng_GadgetText=(STRPTR)"Send";ng.ng_GadgetID=GID_SEND;g->send=CreateGadget(BUTTON_KIND,last,&ng,TAG_DONE);last=g->send;ng.ng_LeftEdge=515;ng.ng_GadgetText=(STRPTR)"Stop";ng.ng_GadgetID=GID_STOP;g->stop=CreateGadget(BUTTON_KIND,last,&ng,GA_Disabled,TRUE,TAG_DONE);last=g->stop;ng.ng_LeftEdge=10;ng.ng_TopEdge=174;ng.ng_Width=555;ng.ng_Height=14;ng.ng_GadgetText=(STRPTR)"Idle";ng.ng_GadgetID=0;g->status=CreateGadget(TEXT_KIND,last,&ng,GTTX_Text,(ULONG)"Idle",GTTX_Border,FALSE,TAG_DONE);last=g->status;ng.ng_LeftEdge=565;ng.ng_TopEdge=18;ng.ng_TopEdge=18;ng.ng_Width=14;ng.ng_Height=125;ng.ng_GadgetText=0;ng.ng_GadgetID=GID_SCROLL;g->scroll=CreateGadget(SCROLLER_KIND,last,&ng,GTSC_Top,0,GTSC_Total,1,GTSC_Visible,1,PGA_Freedom,FREEVERT,TAG_DONE);last=g->scroll;g->window=OpenWindowTags(NULL,WA_Title,(ULONG)"AmiChat",WA_Left,20,WA_Top,20,WA_Width,590,WA_Height,210,WA_MinWidth,400,WA_MinHeight,180,WA_MaxWidth,-1,WA_MaxHeight,-1,WA_DragBar,TRUE,WA_DepthGadget,TRUE,WA_CloseGadget,TRUE,WA_SizeGadget,TRUE,WA_Activate,TRUE,WA_Gadgets,(ULONG)g->gadgets,WA_IDCMP,IDCMP_CLOSEWINDOW|IDCMP_GADGETUP|IDCMP_GADGETDOWN|IDCMP_NEWSIZE|IDCMP_REFRESHWINDOW|IDCMP_RAWKEY,TAG_DONE);if(!g->window){AmiChat_AmigaGUIClose(g);return 0;}AmiChat_TranscriptRebuild(g->transcript,AmiChat_SessionConversation(g->session));sync_scroll(g);GT_RefreshWindow(g->window,NULL);AmiChat_AmigaRendererDraw(g->renderer,g->window);sync_state(g);return g;}
void AmiChat_AmigaGUIClose(AmiChatAmigaGUI*g){if(!g)return;if(g->window)CloseWindow(g->window);if(g->gadgets)FreeGadgets(g->gadgets);if(g->visual)FreeVisualInfo(g->visual);AmiChat_AmigaRendererDestroy(g->renderer);AmiChat_TranscriptDestroy(g->transcript);free(g);}
static void sync_state(AmiChatAmigaGUI*g){AmiChatWorkerState s;const char*name;if(!g||!g->window||!g->worker)return;s=AmiChat_AmigaWorkerState(g->worker);name=AmiChat_WorkerStateName(s);if(g->status)GT_SetGadgetAttrs(g->status,g->window,NULL,GTTX_Text,(ULONG)name,TAG_DONE);if(g->send)GT_SetGadgetAttrs(g->send,g->window,NULL,GA_Disabled,(s==AMICHAT_WORKER_GENERATING||s==AMICHAT_WORKER_CANCELLING),TAG_DONE);if(g->stop)GT_SetGadgetAttrs(g->stop,g->window,NULL,GA_Disabled,(s!=AMICHAT_WORKER_GENERATING),TAG_DONE);}
static void sync_scroll(AmiChatAmigaGUI*g){unsigned long total,visible,top;if(!g||!g->window||!g->scroll)return;total=AmiChat_AmigaRendererTotalLines(g->renderer,g->window);visible=AmiChat_AmigaRendererVisibleLines(g->renderer,g->window);if(!total)total=1;if(!visible)visible=1;if(AmiChat_AmigaRendererFollowing(g->renderer)){top=total>visible?total-visible:0;AmiChat_AmigaRendererSetTopLine(g->renderer,top);AmiChat_AmigaRendererFollow(g->renderer,1);}else top=AmiChat_AmigaRendererTopLine(g->renderer);GT_SetGadgetAttrs(g->scroll,g->window,NULL,GTSC_Total,total,GTSC_Visible,visible,GTSC_Top,top,TAG_DONE);}
unsigned long AmiChat_AmigaGUISignalMask(const AmiChatAmigaGUI*g){return(g&&g->window)?(1UL<<g->window->UserPort->mp_SigBit):0;}
int AmiChat_AmigaGUIHandle(AmiChatAmigaGUI*g){struct IntuiMessage*m;ULONG cls;UWORD code;struct Gadget*gad;int quit=0;if(!g||!g->window)return 0;while((m=GT_GetIMsg(g->window->UserPort))!=0){cls=m->Class;code=m->Code;gad=(struct Gadget*)m->IAddress;GT_ReplyIMsg(m);(void)code;if(cls==IDCMP_REFRESHWINDOW){BeginRefresh(g->window);AmiChat_AmigaRendererDraw(g->renderer,g->window);EndRefresh(g->window,TRUE);}else if(cls==IDCMP_NEWSIZE){sync_scroll(g);AmiChat_AmigaRendererDraw(g->renderer,g->window);}else if(cls==IDCMP_CLOSEWINDOW)quit=1;else if(cls==IDCMP_RAWKEY){if(code==0x4c){AmiChat_AmigaRendererScroll(g->renderer,-1);AmiChat_AmigaRendererDraw(g->renderer,g->window);}else if(code==0x4d){AmiChat_AmigaRendererScroll(g->renderer,1);AmiChat_AmigaRendererDraw(g->renderer,g->window);}}else if(cls==IDCMP_GADGETUP&&gad&&gad->GadgetID==GID_SEND){struct StringInfo*si=(struct StringInfo*)g->prompt->SpecialInfo;if(si&&si->Buffer&&*si->Buffer&&g->worker){AmiChat_TranscriptBegin(g->transcript,AMICHAT_ROLE_USER);AmiChat_TranscriptAppend(g->transcript,(const char*)si->Buffer,strlen((const char*)si->Buffer));AmiChat_TranscriptFinish(g->transcript);sync_scroll(g);AmiChat_AmigaRendererDraw(g->renderer,g->window);if(AmiChat_AmigaWorkerSend(g->worker,(const char*)si->Buffer)==AMICHAT_OK)sync_state(g);}}else if(cls==IDCMP_GADGETUP&&gad&&gad->GadgetID==GID_STOP&&g->worker){AmiChat_AmigaWorkerCancel(g->worker);sync_state(g);}else if((cls==IDCMP_GADGETUP||cls==IDCMP_GADGETDOWN)&&gad&&gad->GadgetID==GID_SCROLL){{ULONG top=0;GT_GetGadgetAttrs(g->scroll,g->window,NULL,GTSC_Top,&top,TAG_DONE);AmiChat_AmigaRendererSetTopLine(g->renderer,top);AmiChat_AmigaRendererDraw(g->renderer,g->window);}}}return quit;}
void AmiChat_AmigaGUIRefreshConversation(AmiChatAmigaGUI*g){if(!g)return;AmiChat_TranscriptRebuild(g->transcript,AmiChat_SessionConversation(g->session));AmiChat_AmigaRendererFollow(g->renderer,1);sync_scroll(g);AmiChat_AmigaRendererDraw(g->renderer,g->window);}
void AmiChat_AmigaGUIWorkerEvent(AmiChatAmigaGUI*g,const AmiChatWorkerEvent*e){if(!g||!e)return;if(e->type==AMICHAT_WORKER_CHUNK){if(!AmiChat_TranscriptActive(g->transcript))AmiChat_TranscriptBegin(g->transcript,AMICHAT_ROLE_ASSISTANT);AmiChat_TranscriptAppend(g->transcript,e->data,e->size);sync_scroll(g);AmiChat_AmigaRendererDraw(g->renderer,g->window);}else if(e->type==AMICHAT_WORKER_DONE||e->type==AMICHAT_WORKER_CANCELLED||e->type==AMICHAT_WORKER_ERROR){AmiChat_TranscriptFinish(g->transcript);sync_state(g);AmiChat_AmigaRendererDraw(g->renderer,g->window);}}
#else
struct AmiChatAmigaGUI { int unused; };
AmiChatAmigaGUI *AmiChat_AmigaGUIOpen(AmiChatSession*s,AmiChatAmigaWorker*w){(void)s;(void)w;return 0;}
void AmiChat_AmigaGUIClose(AmiChatAmigaGUI*g){(void)g;}
unsigned long AmiChat_AmigaGUISignalMask(const AmiChatAmigaGUI*g){(void)g;return 0;}
int AmiChat_AmigaGUIHandle(AmiChatAmigaGUI*g){(void)g;return 0;}
void AmiChat_AmigaGUIWorkerEvent(AmiChatAmigaGUI*g,const AmiChatWorkerEvent*e){(void)g;(void)e;}
void AmiChat_AmigaGUIRefreshConversation(AmiChatAmigaGUI*g){(void)g;}
#endif
