#include "amichat_arexx.h"
#include "amichat_config.h"
#include "amichat_message.h"
#include "amichat_registry.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static const char *skip(const char*s){while(s&&*s&&isspace((unsigned char)*s))s++;return s;}
static int word(const char**sp,char*out,size_t cap){const char*s=skip(*sp);size_t n=0;if(!s||!*s)return 0;while(*s&&!isspace((unsigned char)*s)){if(n+1<cap)out[n++]=*s;s++;}out[n]=0;*sp=s;return n!=0;}
static void ok(AmiChatARexxResult*r,const char*s){r->rc=0;snprintf(r->result,sizeof(r->result),"%s",s?s:"OK");}
static AmiChatResult fail(AmiChatARexxResult*r,AmiChatResult e,const char*s){r->rc=10;snprintf(r->result,sizeof(r->result),"%s",s?s:"ERROR");return e;}
AmiChatResult AmiChat_ARexxDispatch(AmiChatSession*s,const char*command,AmiChatARexxResult*r){char cmd[32],arg[256];const char*p;AmiChatConfig*c;AmiChatResult e;if(!s||!command||!r)return AMICHAT_ERR_INVALID_ARGUMENT;r->rc=10;r->result[0]=0;p=command;if(!word(&p,cmd,sizeof(cmd)))return fail(r,AMICHAT_ERR_INVALID_ARGUMENT,"EMPTY COMMAND");c=AmiChat_SessionConfig(s);if(strcmp(cmd,"NEW")==0){e=AmiChat_SessionNewConversation(s);if(e!=AMICHAT_OK)return fail(r,e,"NEW FAILED");ok(r,"OK");return AMICHAT_OK;}if(strcmp(cmd,"PROVIDER")==0){if(!word(&p,arg,sizeof(arg))){const char*v=AmiChat_ConfigProvider(c);ok(r,v?v:"");return AMICHAT_OK;}e=AmiChat_ConfigSetProvider(c,arg);if(e!=AMICHAT_OK)return fail(r,e,"PROVIDER FAILED");ok(r,arg);return AMICHAT_OK;}if(strcmp(cmd,"MODEL")==0){if(!word(&p,arg,sizeof(arg))){const char*v=AmiChat_ConfigModel(c);ok(r,v?v:"");return AMICHAT_OK;}e=AmiChat_ConfigSetModel(c,arg);if(e!=AMICHAT_OK)return fail(r,e,"MODEL FAILED");ok(r,arg);return AMICHAT_OK;}if(strcmp(cmd,"ENDPOINT")==0){if(!word(&p,arg,sizeof(arg))){const char*v=AmiChat_ConfigEndpoint(c);if(!v){const AmiChatProviderDefinition*d=AmiChat_ProviderDefinitionFind(AmiChat_ConfigProvider(c));v=d?d->default_url:0;}ok(r,v?v:"");return AMICHAT_OK;}e=AmiChat_ConfigSetEndpoint(c,arg);if(e!=AMICHAT_OK)return fail(r,e,"ENDPOINT FAILED");ok(r,arg);return AMICHAT_OK;}if(strcmp(cmd,"SETKEY")==0){p=skip(p);if(!p||!*p)return fail(r,AMICHAT_ERR_INVALID_ARGUMENT,"SETKEY REQUIRES VALUE");e=AmiChat_ConfigSetAPIKey(c,p);if(e!=AMICHAT_OK)return fail(r,e,"SETKEY FAILED");ok(r,"OK");return AMICHAT_OK;}if(strcmp(cmd,"HISTORY")==0){snprintf(r->result,sizeof(r->result),"%lu",(unsigned long)AmiChat_ConversationMessageCount(AmiChat_SessionConversation(s)));r->rc=0;return AMICHAT_OK;}if(strcmp(cmd,"GETMESSAGE")==0){const AmiChatMessage*m;unsigned long i;if(!word(&p,arg,sizeof(arg)))return fail(r,AMICHAT_ERR_INVALID_ARGUMENT,"GETMESSAGE REQUIRES INDEX");i=strtoul(arg,0,10);m=AmiChat_ConversationMessageAt(AmiChat_SessionConversation(s),(size_t)i);if(!m)return fail(r,AMICHAT_ERR_INVALID_ARGUMENT,"MESSAGE NOT FOUND");snprintf(r->result,sizeof(r->result),"%d %s",(int)AmiChat_MessageRole(m),AmiChat_MessageContent(m));r->rc=0;return AMICHAT_OK;}if(strcmp(cmd,"APPLY")==0){e=AmiChat_SessionApplyConfig(s);if(e!=AMICHAT_OK)return fail(r,e,"APPLY FAILED");ok(r,"OK");return AMICHAT_OK;}if(strcmp(cmd,"SEND")==0){p=skip(p);if(!p||!*p)return fail(r,AMICHAT_ERR_INVALID_ARGUMENT,"SEND REQUIRES TEXT");e=AmiChat_SessionSend(s,p,0);if(e!=AMICHAT_OK)return fail(r,e,"SEND FAILED");ok(r,"OK");return AMICHAT_OK;}if(strcmp(cmd,"STATUS")==0){snprintf(r->result,sizeof(r->result),"PROVIDER=%s MODEL=%s MESSAGES=%lu",AmiChat_ConfigProvider(c)?AmiChat_ConfigProvider(c):"",AmiChat_ConfigModel(c)?AmiChat_ConfigModel(c):"",(unsigned long)AmiChat_ConversationMessageCount(AmiChat_SessionConversation(s)));r->rc=0;return AMICHAT_OK;}return fail(r,AMICHAT_ERR_UNSUPPORTED,"UNKNOWN COMMAND");}
