#include "amichat_transport_amiapi.h"
#include <amiapi/amiapi.h>
#include <stdlib.h>
#include <string.h>
typedef struct AmiAPITransportState { struct AmiAPIContext *ctx; char *body; char *content_type; } AmiAPITransportState;
typedef struct CallbackState { AmiChatTransportBodyFn callback; void *userdata; AmiChatResult result; } CallbackState;
static char *copy_bytes(const unsigned char*d,size_t n){char*p=(char*)malloc(n+1);if(!p)return 0;if(n)memcpy(p,d,n);p[n]='\0';return p;}
static void clear_response(AmiAPITransportState*s){free(s->body);s->body=0;free(s->content_type);s->content_type=0;}
static AmiChatResult map_error(enum AmiAPIError e){return e==AMIAPI_OK?AMICHAT_OK:AMICHAT_ERR_NETWORK;}
static enum AmiAPIError body_cb(const void*d,size_t n,void*u){CallbackState*s=(CallbackState*)u;s->result=s->callback(d,n,s->userdata);return s->result==AMICHAT_OK?AMIAPI_OK:AMIAPI_ERR_INTERNAL;}
static AmiChatResult request_fn(AmiChatTransport*t,const AmiChatTransportRequest*q,AmiChatTransportResponse*out){AmiAPITransportState*s;struct AmiAPIRequest*r;struct AmiAPIResponse*rp;enum AmiAPIError e;const char*ct,*h,*line,*colon;char name[128],value[768];size_t n,v;CallbackState cb;if(!t||!q||!out||!q->method||!q->url)return AMICHAT_ERR_INVALID_ARGUMENT;s=(AmiAPITransportState*)t->userdata;if(!s||!s->ctx)return AMICHAT_ERR_INVALID_ARGUMENT;clear_response(s);r=AmiAPI_RequestCreate(s->ctx,q->method,q->url);if(!r)return map_error(AmiAPI_LastError(s->ctx));h=q->headers;while(h&&*h){line=strstr(h,"\r\n");if(!line)line=h+strlen(h);colon=(const char*)memchr(h,':',(size_t)(line-h));if(colon){n=(size_t)(colon-h);while(n&&h[n-1]==' ')n--;v=(size_t)(line-colon-1);while(v&&colon[1]==' '){colon++;v--;}if(n<sizeof(name)&&v<sizeof(value)){memcpy(name,h,n);name[n]='\0';memcpy(value,colon+1,v);value[v]='\0';e=AmiAPI_RequestSetHeader(r,name,value);if(e!=AMIAPI_OK){AmiAPI_RequestDestroy(r);return map_error(e);}}}h=*line?line+2:line;}if(q->body){e=AmiAPI_RequestSetBody(r,q->body,strlen(q->body));if(e!=AMIAPI_OK){AmiAPI_RequestDestroy(r);return map_error(e);}}cb.callback=q->body_callback;cb.userdata=q->body_userdata;cb.result=AMICHAT_OK;if(q->body_callback){e=AmiAPI_RequestSetResponseCallback(r,body_cb,&cb);if(e!=AMIAPI_OK){AmiAPI_RequestDestroy(r);return map_error(e);}}rp=AmiAPI_RequestExecute(r);if(!rp){e=AmiAPI_LastError(s->ctx);AmiAPI_RequestDestroy(r);if(cb.result!=AMICHAT_OK)return cb.result;return map_error(e);}out->status_code=(long)AmiAPI_Status(rp);if(!q->body_callback&&AmiAPI_Body(rp)){s->body=copy_bytes(AmiAPI_Body(rp),AmiAPI_BodySize(rp));if(!s->body){AmiAPI_FreeResponse(rp);AmiAPI_RequestDestroy(r);return AMICHAT_ERR_NOMEM;}}ct=AmiAPI_Header(rp,"Content-Type");if(ct)s->content_type=copy_bytes((const unsigned char*)ct,strlen(ct));out->body=s->body;out->content_type=s->content_type;AmiAPI_FreeResponse(rp);AmiAPI_RequestDestroy(r);return cb.result;}
static void destroy_fn(AmiChatTransport*t){AmiAPITransportState*s;if(!t)return;s=(AmiAPITransportState*)t->userdata;if(s){clear_response(s);if(s->ctx)AmiAPI_Destroy(s->ctx);free(s);}free(t);}
static const AmiChatTransportOps ops={request_fn,destroy_fn};
AmiChatTransport *AmiChat_AmiAPITransportCreate(void){AmiChatTransport*t=(AmiChatTransport*)calloc(1,sizeof(*t));AmiAPITransportState*s;if(!t)return 0;s=(AmiAPITransportState*)calloc(1,sizeof(*s));if(!s){free(t);return 0;}s->ctx=AmiAPI_Create();if(!s->ctx){free(s);free(t);return 0;}t->ops=&ops;t->userdata=s;return t;}
