#include "amichat_openai_compat.h"
#include "amichat_json.h"
#include "amichat_sse.h"
#include "amichat_message.h"
#include <stdlib.h>
#include <string.h>
typedef struct OpenAICompatState { AmiChatTransport *transport; char *base_url; char *api_key; char *organization; } OpenAICompatState;
typedef struct SSEBridge { AmiChatSSEParser parser; } SSEBridge;
static char*dupstr(const char*s){size_t n;char*p;if(!s)return 0;n=strlen(s)+1;p=(char*)malloc(n);if(p)memcpy(p,s,n);return p;}
static void freestate(OpenAICompatState*s){if(!s)return;free(s->base_url);free(s->api_key);free(s->organization);free(s);}
static AmiChatResult configure(AmiChatProvider*p,const char*c){(void)p;(void)c;return AMICHAT_ERR_UNSUPPORTED;}
static AmiChatResult models(AmiChatProvider*p){(void)p;return AMICHAT_ERR_UNSUPPORTED;}
static AmiChatResult sendfn(AmiChatProvider*p,AmiChatConversation*c){(void)p;(void)c;return AMICHAT_ERR_UNSUPPORTED;}
static AmiChatResult cancel(AmiChatProvider*p){(void)p;return AMICHAT_ERR_UNSUPPORTED;}
static void destroy(AmiChatProvider*p){if(p){freestate((OpenAICompatState*)p->userdata);p->userdata=0;}}
static const AmiChatProviderOps ops={configure,models,sendfn,cancel,destroy};
static AmiChatResult sse_body(const void*d,size_t n,void*u){SSEBridge*b=(SSEBridge*)u;return AmiChat_SSEFeed(&b->parser,(const char*)d,n);}
AmiChatResult AmiChat_OpenAICompat_Init(AmiChatProvider*p,AmiChatTransport*t,const AmiChatOpenAICompatConfig*c){OpenAICompatState*s;if(!p||!t||!c||!c->base_url)return AMICHAT_ERR_INVALID_ARGUMENT;s=(OpenAICompatState*)calloc(1,sizeof(*s));if(!s)return AMICHAT_ERR_NOMEM;s->transport=t;s->base_url=dupstr(c->base_url);s->api_key=dupstr(c->api_key);s->organization=dupstr(c->organization);if(!s->base_url||(c->api_key&&!s->api_key)||(c->organization&&!s->organization)){freestate(s);return AMICHAT_ERR_NOMEM;}p->ops=&ops;p->userdata=s;return AMICHAT_OK;}
AmiChatResult AmiChat_OpenAICompat_Chat(AmiChatProvider*p,const AmiChatRequest*r,AmiChatStream*s){OpenAICompatState*st;SSEBridge bridge;char body[4096],headers[1024],content[2048];size_t n=0;AmiChatTransportRequest tr;AmiChatTransportResponse tp;AmiChatResult e;int streaming;if(!p||!r)return AMICHAT_ERR_INVALID_ARGUMENT;e=AmiChat_RequestValidate(r);if(e!=AMICHAT_OK)return e;st=(OpenAICompatState*)p->userdata;if(!st)return AMICHAT_ERR_INVALID_ARGUMENT;streaming=s!=0;if(n+1>=sizeof(body))return AMICHAT_ERR_NOMEM;body[n++]='{';body[n]='\0';if(AmiChat_JSONAppendString(body,sizeof(body),&n,"model")!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;if(n+1>=sizeof(body))return AMICHAT_ERR_NOMEM;body[n++]=':';body[n]='\0';if(AmiChat_JSONAppendString(body,sizeof(body),&n,r->model)!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;{const char tail[]=",\"messages\":[{\"role\":\"user\",\"content\":";size_t tl=sizeof(tail)-1;if(n+tl>=sizeof(body))return AMICHAT_ERR_NOMEM;memcpy(body+n,tail,tl);n+=tl;body[n]='\0';}if(AmiChat_JSONAppendString(body,sizeof(body),&n,r->user_prompt)!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;{const char tail[]="}],\"stream\":";size_t tl=sizeof(tail)-1;if(n+tl+6>=sizeof(body))return AMICHAT_ERR_NOMEM;memcpy(body+n,tail,tl);n+=tl;memcpy(body+n,streaming?"true}":"false}",streaming?5:6);n+=streaming?5:6;body[n]='\0';}strcpy(headers,"Content-Type: application/json\r\nAccept: application/json\r\n");if(st->api_key){if(strlen(headers)+strlen(st->api_key)+25>=sizeof(headers))return AMICHAT_ERR_NOMEM;strcat(headers,"Authorization: Bearer ");strcat(headers,st->api_key);strcat(headers,"\r\n");}if(st->organization){if(strlen(headers)+strlen(st->organization)+24>=sizeof(headers))return AMICHAT_ERR_NOMEM;strcat(headers,"OpenAI-Organization: ");strcat(headers,st->organization);strcat(headers,"\r\n");}tr.method="POST";tr.url=st->base_url;tr.headers=headers;tr.body=body;tr.body_callback=0;tr.body_userdata=0;if(streaming){AmiChat_SSEInit(&bridge.parser,s);tr.body_callback=sse_body;tr.body_userdata=&bridge;}e=AmiChat_TransportRequest(st->transport,&tr,&tp);if(e!=AMICHAT_OK)return e;if(tp.status_code<200||tp.status_code>=300)return AMICHAT_ERR_PROVIDER;if(streaming)return AmiChat_SSEFinish(&bridge.parser);if(!tp.body)return AMICHAT_ERR_PROVIDER;if(!AmiChat_JSONFindString(tp.body,"content",content,sizeof(content)))return AMICHAT_ERR_PROVIDER;return AMICHAT_OK;}

static const char *conversation_role(AmiChatRole r){switch(r){case AMICHAT_ROLE_SYSTEM:return "system";case AMICHAT_ROLE_USER:return "user";case AMICHAT_ROLE_ASSISTANT:return "assistant";case AMICHAT_ROLE_TOOL:return "tool";default:return "user";}}
static int append_raw(char*b,size_t cap,size_t*n,const char*s){size_t l=strlen(s);if(*n+l>=cap)return 0;memcpy(b+*n,s,l);*n+=l;b[*n]=0;return 1;}
AmiChatResult AmiChat_OpenAICompat_Conversation(AmiChatProvider*p,const char*model,const AmiChatConversation*c,AmiChatStream*s){OpenAICompatState*st;char body[16384],headers[1024],content[2048];size_t n=0,i,count;const AmiChatMessage*m;AmiChatTransportRequest tr;AmiChatTransportResponse tp;AmiChatResult e;SSEBridge bridge;if(!p||!model||!*model||!c)return AMICHAT_ERR_INVALID_ARGUMENT;st=(OpenAICompatState*)p->userdata;if(!st)return AMICHAT_ERR_INVALID_ARGUMENT;if(!append_raw(body,sizeof(body),&n,"{\"model\":"))return AMICHAT_ERR_NOMEM;if(AmiChat_JSONAppendString(body,sizeof(body),&n,model)!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;if(!append_raw(body,sizeof(body),&n,",\"messages\":["))return AMICHAT_ERR_NOMEM;count=AmiChat_ConversationMessageCount(c);for(i=0;i<count;i++){m=AmiChat_ConversationMessageAt(c,i);if(!m)continue;if(i&&!append_raw(body,sizeof(body),&n,","))return AMICHAT_ERR_NOMEM;if(!append_raw(body,sizeof(body),&n,"{\"role\":"))return AMICHAT_ERR_NOMEM;if(AmiChat_JSONAppendString(body,sizeof(body),&n,conversation_role(AmiChat_MessageRole(m)))!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;if(!append_raw(body,sizeof(body),&n,",\"content\":"))return AMICHAT_ERR_NOMEM;if(AmiChat_JSONAppendString(body,sizeof(body),&n,AmiChat_MessageContent(m))!=AMICHAT_OK)return AMICHAT_ERR_NOMEM;if(!append_raw(body,sizeof(body),&n,"}"))return AMICHAT_ERR_NOMEM;}if(!append_raw(body,sizeof(body),&n,s?"],\"stream\":true}":"],\"stream\":false}"))return AMICHAT_ERR_NOMEM;strcpy(headers,"Content-Type: application/json\r\nAccept: application/json\r\n");if(st->api_key){strcat(headers,"Authorization: Bearer ");strcat(headers,st->api_key);strcat(headers,"\r\n");}if(st->organization){strcat(headers,"OpenAI-Organization: ");strcat(headers,st->organization);strcat(headers,"\r\n");}tr.method="POST";tr.url=st->base_url;tr.headers=headers;tr.body=body;tr.body_callback=0;tr.body_userdata=0;if(s){AmiChat_SSEInit(&bridge.parser,s);tr.body_callback=sse_body;tr.body_userdata=&bridge;}e=AmiChat_TransportRequest(st->transport,&tr,&tp);if(e!=AMICHAT_OK)return e;if(tp.status_code<200||tp.status_code>=300)return AMICHAT_ERR_PROVIDER;if(s)return AmiChat_SSEFinish(&bridge.parser);if(!tp.body||!AmiChat_JSONFindString(tp.body,"content",content,sizeof(content)))return AMICHAT_ERR_PROVIDER;return AMICHAT_OK;}
