name: amiga-ci

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  amiga:
    uses: Ploos-AS/amiga-dev/.github/workflows/reusable-amiga-dev.yml@main
    with:
      image: ghcr.io/ploos-as/amiga-dev:edge
      command: git clone --depth 1 https://github.com/pgousdal/AmiAPI.git /tmp/AmiAPI && make -C /tmp/AmiAPI PLATFORM=amiga CFLAGS='-Os -Wall -Wextra -m68000' build/libamiapi.a && make amiga-link AMIAPI_DIR=/tmp/AmiAPI
